const POINT_TYPES = ['taxi', 'bus', 'flight'];

const DATE_FORMAT_DAY_AND_MONTH = 'D MMMM';
const DATE_FORMAT_TIME_ONLY = 'HH:mm';
const DATE_FORMAT_DATE_AND_TIME = 'DD/MM/YY HH:mm';

const DESTINATIONS_COUNT = 5;

export { POINT_TYPES, DATE_FORMAT_DAY_AND_MONTH, DATE_FORMAT_TIME_ONLY, DESTINATIONS_COUNT, DATE_FORMAT_DATE_AND_TIME };
